projects:
  app:
    # schema: http://localhost:8000/___graphql
    schema: 'graphql/schema.graphql'
    include: 'src/**/*.tsx'
    schemaPath: 'graphql/schema.graphql'
    extensions:
      endpoints:
        default: http://localhost:8000/___graphql
      schemaTypesPath: src/schema
